### ISSUE TITLE
Retranslate Portuguese A3 poster

### ISSUE THREAD

**Issue by sagesharp** [outreachy/creative-works-and-scripts#10]
The language in the English U.S. letter and A4 posters has changed. I've attempted to retranslate the Brazil A3 poster (and update the dates) but I need a native Brazilian Portuguese speaker to double check it.

**Comment by sagesharp** [comment]
The English A4 poster is here: https://github.com/sagesharp/outreachy/blob/master/creative-works/poster-applicants-A4.svg

The Brazilian Portuguese A3 poster is here: https://github.com/sagesharp/outreachy/blob/master/creative-works/poster-applicants-A3-Brasil.svg
Please also save the poster as a PDF and push to this file: https://github.com/sagesharp/outreachy/blob/master/creative-works/poster-applicants-A4-Brasil.pdf

Editing in Inkscape is encouraged. Please make sure to convert text to paths when saving as a PDF.

**Comment by yogmel** [comment]
Hi Sage,
I'm a Brazilian native and I can check the translation. I can get back to you today. Does that sound good?

Just to confirm, I have to make a pull request to change [this file](https://github.com/sagesharp/outreachy/blob/master/creative-works/poster-applicants-A4-Brasil.pdf), right?

**Comment by yogmel** [comment]
Actually it looks **pretty good** already haha I'll just change some text to be more natural.

**Comment by contraexemplo** [comment]
I'll see if I can edit it myself, but the translation goes like this:

> Outreachy convida pessoas dos seguintes grupos a se candidatarem:
> - Mulheres (cis & trans), homens trans, ou pessoas genderqueer
> - Pessoas residentes ou cidadãs dos Estados Unidos de qualquer gênero que sejam:
>    + Negras/Afro-americanas
>    + Hispânicas/latinas,
>    + Nativo americanas/Índio americanas, nativo alasquianas, nativo havainas ou ilhéus do Pacífico
> - Qualquer pessoa que enfrente opressão ou discriminação sistemática na indústria da tecnologia ou em seu país

I've made some changes to make it sound more natural in Brazilian Portuguese:
- Didn't translate "expressly".
- Used "person" as a way to make language more neutral (Portuguese has this problem with gendered words).
- Changed "systematic bias or discrimination" to "opressão ou discriminação sistemática".

What do you think, @yogmel?

**Comment by sagesharp** [comment]
Does the word "expressly" not translate at all? If not, that's ok. The English version is meant to be a bit more formal to indicate that the invitation is very emphatic. Sort of a "yes, really, this invitation is for you" word.

Thanks for the update on gender-neutral language!

**Comment by contraexemplo** [comment]
@sagesharp It does -- "expressadamente". If added, the phrase will be like this:

> Outreachy expressadamente convida pessoas dos seguintes grupos a se candidatarem:

I was also a bit worried about the length of that phrase, but as your intention is being emphatic, it is a good idea to keep that adverb there.

**Comment by sagesharp** [comment]
My Spanish is very rusty (and I don't know how much it helps with Portuguese). Does Negras imply a group of Black women? Or a group of Black people with many different gender identities? Same for the endings on the other U.S. ethnic groups.

**Comment by contraexemplo** [comment]
> Does Negras imply a group of Black women? Or a group of Black people with many different gender identities?

"Pessoa" (person in Portuguese) is a feminine word. That's why every adjective related to it will usually carry an "a" at the end of it. I translated

> U.S. residents & nationals of any gender who are:

into

> Pessoas residentes ou cidadãs dos Estados Unidos de qualquer gênero que sejam:

to make sure it would include people from any gender.

There's a great discussion about colorism and identity in black communities in Brazil. Some people identify as "pardos" (https://en.wikipedia.org/wiki/Pardo_Brazilians), some people reject that identity. As you're referring to the US context, I think it's fine to keep it as "[pessoas] negras/afro americanas".

**Comment by yogmel** [comment]
Hi @contraexemplo,
Good that you came in, I was going to change the already translated text (? confusing, I know).

I think your translation is pretty accurate. Using 'person' is a very actual way to be neutral, as is used in job posting, by companies that do care about gender neutrality/diversity.
e.g.: 'Pessoa desenvolvedora de software'

About 'expressadamente', I think it's better to be left out, unless we find a better word for it. I'll have a look.

Once we agree on a translated text, I can change the poster if you want :)

**Comment by contraexemplo** [comment]
> About 'expressadamente', I think it's better to be left out, unless we find a better word for it. I'll have a look.

Yeah, I'm quite worried about it being too wordly because it's an A3 poster. I'd have to make some tests to know if I would be able to read it by myself or if I would need help from others (I'm visually impaired and I'm afraid that the more words we add, the smaller the whole text will be).

**Comment by yogmel** [comment]
Oh I understand! My sister is also visually impaired and I'm aware that there are some things we must do to make it accessible to everybody.
I will send you an email btw. I realized just now that there is no messaging system in Github hahaha

**Comment by phls** [comment]
@contraexemplo Hi.

Last year when I transleted the banner, I had removed the part about "Pessoas residentes ou cidadãs dos Estados Unidos" because I believe it's not necessary to use it here in Brazil.

**Comment by contraexemplo** [comment]
@phls That's a good point!

**Comment by phls** [comment]
> > Outreachy expressadamente convida pessoas dos seguintes grupos a se candidatarem:

Isn't is:

Outreachy convida espressamente pessoas dos seguintes grupos a se candidatarem:

**Comment by phls** [comment]
> @phls That's a good point!

Nice. If we remove this part, we will have more space :-)

**Comment by contraexemplo** [comment]
@phls yeah, expressamente is way more used than expressadamente. Good call.

**Comment by contraexemplo** [comment]
So, just to update the whole text based on our discussions, it would be like this:

> Outreachy expressamente convida a se candidatarem:
> - Mulheres (cis & trans), homens trans, ou pessoas genderqueer
 > - Qualquer pessoa que enfrente opressão ou discriminação sistemática na indústria da tecnologia ou em seu país

as these are the groups probable Brazilians candidates may belong. Took "pessoas dos seguintes grupos" off as it doesn't seem necessary now.

**Comment by sagesharp** [comment]
If that's the final text, I'm happy to update the files and give everyone credit!

**Comment by contraexemplo** [comment]
@sagesharp I think it's great the way it is now.

@phls @yogmel is there anything else you would like to add?

**Comment by yogmel** [comment]
It looks great for me :)

**Comment by phls** [comment]
@sagesharp would you like I write the svg file?

**Comment by sagesharp** [comment]
@phls No thank you, I have the svg files in front of me and I can edit them. Thank you so much for your help @phls @yogmel @contraexemplo !!

**Comment by contraexemplo** [comment]
You're welcome, @sagesharp!

**Comment by phls** [comment]
Nice :-)
