### ISSUE TITLE
Communities should not get the option to Start Initial Application

### ISSUE THREAD

**Issue by shivan1b** [outreachy/creative-works-and-scripts#16]
Currently in the Dashboard, anybody who has logged in gets a dialog box to "Start Initial Application". This should only be visible to prospective interns.
This happens on the `/dashboard` URL.

**Comment by vipul-aggarwal-099** [comment]
I am interested with issue to fix.

**Comment by sagesharp** [comment]
This issue should have been filed against the Outreachy website repository, not the creative works respository. If this issue is still unresolved, please file it [here](https://github.com/outreachy/website/issues/).
